version: "3.8"

services:
  db:
    container_name: devlinks-container
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - devlinks-data:/var/lib/postgresql/data

volumes:
  devlinks-data:
