import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import Navbar from "@/components/ui/navbar/Navbar";

const intrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ConfigurationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={intrumentSans.className}>
        <div>
          <main className="h-full w-full bg-gray-light">
            <div className="pt-4">
              <Navbar />
            </div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
