import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const intrumentSans = Instrument_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={intrumentSans.className}>
        <div className="h-screen bg-gray-light">{children}</div>
      </body>
    </html>
  );
}
